baseURL = "http://tsdiokno.github.io/abl"
languageCode = "en-us"
publishDir = "docs"
title = "Ang Biblia ng Lahat (ABL)"
theme = "book"

enableGitInfo = true

[params]
  BookLogo = 'ABL_Logo_v2.png'
  BookMenuBundle = "/menu"
  BookRepo = "https://github.com/tsdiokno/abl"
  BookEditPath = "edit/master/content"
